security:
    providers:
        user_db_provider:
            entity:
                class: App\Entity\User
                property: apiKey
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$LhoRWwnWimLqBjFeXOD59ObHQlALhaZh2pqkGzzTIrXeFZs/ltSju
                        roles: 'ROLE_ADMIN'
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    role_hierarchy:
        ROLE_ADMIN: [ROLE_API]
    firewalls:
        api:
            pattern: ^/api/
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            provider: user_db_provider
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic: true
            provider: in_memory
    access_control:
        - { path: ^/api/, roles: ROLE_API }
        - { path: ^/admin/, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        App\Entity\User:
            algorithm: auto

